# Generated by Django 4.0 on 2021-12-29 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_date_create_alumno_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
