# Generated by Django 4.0 on 2022-01-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('alumnos', '0006_alumno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('name',)},
        ),
    ]
